### ISSUE TITLE
What is that ? 

### ISSUE THREAD

**Issue by servatj** [Ccastillo06/advent-of-code-2020#1]
A code challenge before Christmas?

**Comment by Ccastillo06** [comment]
Hi @servatj ! I'm making a repo with the solutions I achieve when doing the **Advent of Code** for this year 😄  

Here's the link:  **https://adventofcode.com/**

It gets harder as more time passes, let's try to complete as much as we can! 💪

**Comment by servatj** [comment]
Ok cool thanks for the link :100:
